---

- name: Deploy code for api.languagedepot.org
  hosts: all
  become: no
  tasks:
    - name: composer install
      command: composer install
      args:
        chdir: "{{item}}"
      changed_when: false
      when: inventory_hostname == "localhost"
      with_items:
        - /var/www/languagedepot.org_api/htdocs

    - name: bower install
      command: bower install --allow-root
      args:
        chdir: "{{item}}"
      changed_when: false
      when: inventory_hostname == "localhost"
      with_items:
        - /var/www/languagedepot.org_api/htdocs
