---

- name: Deploy development environment for languagedepot.org
  hosts: all
  become: yes
  vars_files:
    - [ "vars/{{ ansible_distribution_release }}.yml", "vars/os_defaults.yml" ]
  pre_tasks:
    - name: Get local dir (localhost)
      local_action: shell pwd
      register: local_dir
      when: inventory_hostname == "localhost"
    - include_vars: "vars/{{ deploy }}.yml"
    - name: install packages needed for roles
      apt: name="{{item}}" state=present
      with_items:
        - libapache2-mod-perl2
  roles:
    - fix
    # locale_install may be needed if locale has been changed away from defaults
    # - locale_install
    - apache_config
  tasks:
    - name: install packages
      apt: name="{{item}}" state=present
      with_items: "{{ dependencies_packages }}"

    - name: php log folder exists
      file: path={{php_log_folder}} state=directory owner=www-data group=www-data mode=0775 recurse=yes

    - name: php.ini changes
      lineinfile:
        dest: "{{php_path}}/apache2/php.ini"
        regexp: '^;?{{item.property}}'
        line: "{{item.property}} = {{item.value}}"
        backrefs: yes
      with_items:
        - property: 'display_errors'
          value: 'On'
        - property: 'display_startup_errors'
          value: 'On'
        - property: 'error_log'
          value: '{{php_log_folder}}/php_error.log'
      notify: Restart apache

    - name: php enable modules
      command: "phpenmod {{item}}"
      args:
        creates: "{{php_path}}/apache2/conf.d/20-{{item}}.ini"
      with_items:
        - pdo_mysql
      notify: Restart apache

    - name: cache folder exists
      file: path={{cache_path}} state=directory owner=www-data group=www-data mode=0775 recurse=yes

    - name: VCS folder exists
      file: path={{vcs_path}} state=directory owner=www-data group=www-data mode=0775 recurse=yes

    - name: resumable API folder exists
      file: path={{resumable_api_path}} state=directory owner=www-data group=www-data mode=0775 recurse=yes

    - name: add host aliases
      lineinfile:
        dest: /etc/hosts
        regexp: '\s{{item}}'
        line: "127.0.0.1    {{item}}"
        state: present
        create: yes
      with_items:
        - "languagedepot.local"
        - "api.languagedepot.local"
        - "admin.languagedepot.local"
        - "hg-public.languagedepot.local"
        - "resumable.languagedepot.local"
