---

- name: Linux Debian webserver (usually in VM)
  hosts: all
  become: yes
  tasks:
    - name: install packages
      apt: name="{{item}}" state=present
      with_items:
        - gcc

- include: dependencies.yml
  vars:
    deploy: palaso
    php_ini_path: /etc/php5/apache2/php.ini
- include: code.yml
