---

php_log_folder: /var/log/php
repo_path: "{{local_dir.stdout | dirname | realpath}}"

apache_module_enable:
  - cgi
  - perl
  - proxy
  - proxy_http
  - rewrite
  - ssl

apache_site_enable:
  - languagedepot_org.conf
  - languagedepot_org_api.conf

apache_vhosts:
  - server_name: languagedepot.org
    server_admin: webmaster@palaso.org
    server_file_name: languagedepot_org
    template: vhost_proxy_ssl.conf.j2
    virtual_hosts:
      - has_ssl: false
        port: 80
        server_alias:
          - languagedepot.local
        proxy: "http://localhost:3001/"
  - server_name: api.languagedepot.org
    server_admin: webmaster@palaso.org
    server_file_name: languagedepot_org_api
    template: vhost_ssl.conf.j2
    document_root: /var/www/languagedepot.org_api/htdocs
    link_to: "{{repo_path}}/src"
    directory_extra:
      - RewriteEngine On
    virtual_hosts:
      - has_ssl: false
        port: 80
        server_alias:
          - api.languagedepot.local
          - admin.languagedepot.local
  - server_name: hg-public.languagedepot.org
    server_admin: webmaster@palaso.org
    server_file_name: languagedepot_org_hg-public
    document_root: /var/www/languagedepot.org_hg-public/htdocs
    template: vhost_ssl.conf.j2
#    template: vhost_perl_ssl.conf.j2
    virtual_hosts:
      - has_ssl: false
        port: 80
        server_alias:
          - hg-public.languagedepot.local
        extra:
          - "LimitRequestLine 16330"
          - "ScriptAliasMatch ^(.*) /var/www/languagedepot.org_hg-public/cgi-bin/hgwebdir.cgi$1"
#          - "PerlRequire /var/www/languagedepot.org_hg-public/contrib/RedminePublic.pm"
#        has_cgi: true
#        auth_location:
#          location: "/"
#          auth_type: "Basic"
#          auth_name: "Language Depot Public Repository"
#          extra:
#            - 'PerlAccessHandler Apache::Authn::RedminePublic::access_handler'
#            - 'PerlAuthenHandler Apache::Authn::RedminePublic::authen_handler'
#            - 'PerlSetVar dsn "DBI:mysql:database=languagedepot;host=localhost"'
#            - 'PerlSetVar db_user test'
#            - 'PerlSetVar db_pass tset23'
